# Generated by Django 5.1 on 2024-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='guess_name',
            new_name='guest_name',
        ),
    ]
